name: Run World Bank Scraper Daily

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Write Google credentials to file
      run: |
        cat <<EOF > google_service_account.json
        ${{ secrets.GOOGLE_CREDENTIALS }}
        EOF

    - name: Download previous Excel artifact
      uses: actions/download-artifact@v4
      with:
        name: latest-worldbank-data
        path: .
      continue-on-error: true

    - name: Debug: list files
      run: ls -lah

    - name: Run script
      run: python main.py

    - name: Upload updated Excel file
      uses: actions/upload-artifact@v4
      with:
        name: latest-worldbank-data
        path: worldbank_current_opportunities.xlsx
